# GitHub Pages specific configuration
# This overrides settings for GitHub Pages environment

# Ensure baseurl is correctly set for GitHub Pages
baseurl: ""  # Adjust if your repo name is different

# GitHub Pages specific settings
github:
  is_project_page: true
  repository_url: "https://github.com/jtay/shoehive"
  
# Ensure plugins are GitHub Pages compatible
plugins:
  - jekyll-feed

# Keep the same theme
theme: just-the-docs