name: Generate API Documentation

on:
  # Run manually from the Actions tab
  workflow_dispatch:
  
  # Run when source code changes
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'typedoc.json'
      - 'docs/generate-api-docs.js'

# Sets permissions of the GITHUB_TOKEN to allow pushing back to the repository
permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate documentation
        run: npm run docs:generate
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add all generated API documentation
          git add docs/pages/api/reference.md
          git add docs/pages/api/index.md
          git add docs/pages/api/generated/index.md
          # Don't add other generated files as they're in .gitignore
          git commit -m "Update API documentation" || echo "No changes to commit"
          git push 